[phases.setup]
nixPkgs = ["python311", "gcc", "unixodbc"]

[phases.install]
cmds = ["cd reporting-backend && pip install -r requirements.txt"]

[start]
cmd = "cd reporting-backend && gunicorn --bind 0.0.0.0:$PORT src.main:app"