[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd reporting-backend && gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 src.main:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ALWAYS"