[phases.setup]
nixPkgs = ["python311", "gcc", "unixODBC", "freetds"]
aptPkgs = ["unixodbc-dev", "freetds-dev", "freetds-bin", "tdsodbc"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT src.main:app"

[variables]
ACCEPT_EULA = "Y"